# Generated by Django 3.2.7 on 2021-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('yb_stuid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('yb_realname', models.CharField(max_length=10, verbose_name='姓名')),
                ('yb_id', models.IntegerField(verbose_name='易班学号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('yb_classname', models.CharField(default='暂无信息', max_length=20, null=True, verbose_name='班级')),
                ('yb_collegename', models.CharField(default='暂无信息', max_length=15, null=True, verbose_name='二级学院')),
            ],
            options={
                'verbose_name': 'stu',
                'verbose_name_plural': 'stus',
                'db_table': 'stu_info',
            },
        ),
        migrations.CreateModel(
            name='StuUpload',
            fields=[
                ('stuid', models.CharField(max_length=12)),
                ('recode_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录id')),
                ('upload_name', models.CharField(max_length=30, verbose_name='文件名')),
                ('upload_type', models.IntegerField(choices=[(1, 'type_1'), (2, 'type_2'), (3, 'type_3')], verbose_name='作品类型')),
                ('upload_state', models.IntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '审核不通过'), (4, '已被征稿')], verbose_name='作品状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'opus',
                'verbose_name_plural': 'opus',
                'db_table': 'stu_upload',
                'unique_together': {('stuid', 'upload_type')},
            },
        ),
    ]
